### ISSUE TITLE
其实 obj 等构建生成的文件不应该上传

### ISSUE THREAD

**Issue by lindexi** [hoge-jafer/carlen#1]

**Comment by hoge-jafer** [comment]
https://social.microsoft.com/Forums/zh-CN/c64fb40f-e926-4e04-9a3c-eb03a1daccbc/36825200102608521382255112021422914203092591327169264956529236?forum=wpfzhchs 我这是上传这个demo的，报了个错。

**Comment by hoge-jafer** [comment]
谢谢提醒
